import AppNavigation from '@/components/AppNavigation'
import { ReactNode } from 'react'
import '@/app/globals.css'


export const metadata = {
  title: '1Kball App V2',
  description: 'Generated by create next app',
}

// This component is a wrapper for all the pages in the application

export default function RootLayout({ children}: {children: ReactNode }) {

  return (
    <html lang="en">
      <body>
       <AppNavigation/>
        {children}
      </body>
    </html>
  )
}
